language: python
sudo: false
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: pypy3

branches:
  only:
    - master
    - v1.x

cache: pip
install:
    - python --version
    - pip --version
    - pip install tox
script:
    - tox -e py

notifications:
  email:
    on_success: never
    on_failure: change
